server:
  port: 8081

spring:
  datasource:
    username: dev
    password: test1234
    url: jdbc:mysql://localhost:3306/ur2lng?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update