server:
  port: 8081

spring:
  datasource:
    username: dev
    password: test1234
    url: jdbc:mysql://localhost:3306/ur2lng?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false

  jpa:
    hibernate:
      ddl-auto: true #only true for dev purposes